config/routes.rb
Rails.application.routes.draw do
  resources :encounters
  resources :patients
  root 'patients#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/encounter.rb
class Encounter < ApplicationRecord
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :encounters, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  before_action :set_encounter, only: [:show, :edit, :update, :destroy]

  # GET /encounters
  # GET /encounters.json
  def index
    @encounters = Encounter.all
  end

  # GET /encounters/1
  # GET /encounters/1.json
  def show
    @patient = Patient.find(@encounter.patient_id)
  end

  # GET /encounters/new
  def new
    @patient = Patient.find(params[:patient_id])
    @encounter = Encounter.new(:patient_id => params[:patient_id])
  end

  # GET /encounters/1/edit
  def edit
    @patient = Patient.find(@encounter.patient_id)
  end

  # POST /encounters
  # POST /encounters.json
  def create
    @encounter = Encounter.new(encounter_params)
    @patient = Patient.find(@encounter.patient_id)

    respond_to do |format|
      if @encounter.save
        format.html { redirect_to @patient, notice: 'Encounter was successfully created.' }
        format.json { render :show, status: :created, location: @encounter }
      else
        format.html { render :new }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encounters/1
  # PATCH/PUT /encounters/1.json
  def update
    @patient = Patient.find(@encounter.patient_id)
    
    respond_to do |format|
      if @encounter.update(encounter_params)
        format.html { redirect_to @patient, notice: 'Encounter was successfully updated.' }
        format.json { render :show, status: :ok, location: @encounter }
      else
        format.html { render :edit }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encounters/1
  # DELETE /encounters/1.json
  def destroy
    @patient = Patient.find(@encounter.patient_id)
    @encounter.destroy
    respond_to do |format|
      format.html { redirect_to @patient, notice: 'Encounter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encounter
      @encounter = Encounter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encounter_params
      params.require(:encounter).permit(:visit_number, :admitted_at, :discharged_at, :location, :room, :bed, :patient_id)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to root_url, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to root_url, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :middle_name, :last_name, :weight, :height, :mrn)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/encounters/_form.html.erb
<%= form_for encounter, :html => {:class => "form-horizontal"} do |f| %>
  
  <% if encounter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(encounter.errors.count, "error") %> prohibited this encounter from being saved:</h2>

      <ul>
      <% encounter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :visit_number, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :visit_number, :class => "form-control", :placeholder => "Visit Number", :required => true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :admitted_at, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :admitted_at, :class => "form-control", :placeholder => "Admitted At", :id => "admitted-at-datetime", :required => true %>
    </div>
    <script type="text/javascript">
        $(function () {
            $('#admitted-at-datetime').datetimepicker({
              format: 'YYYY-MM-DD HH:mm:ss'
            });
        });
    </script>
  </div>

  <div class="form-group">
    <%= f.label :discharged_at, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :discharged_at, :class => "form-control", :placeholder => "Discharged At", :id => "discharged-at-datetime" %>
    </div>
    <script type="text/javascript">
        $(function () {
            $('#discharged-at-datetime').datetimepicker({
              format: 'YYYY-MM-DD HH:mm:ss'
            });
        });
    </script>
  </div>

  <div class="form-group">
    <%= f.label :location, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :location, :class => "form-control", :placeholder => "Location" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :room, :class => "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.number_field :room, :class => "form-control", :placeholder => "Room" %>
    </div>
    <%= f.label :bed, :class => "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.number_field :bed, :class => "form-control", :placeholder => "Bed" %>
    </div>
  </div>

  <%= f.hidden_field :patient_id %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit params[:action] == "new" ? "Submit" : "Update", :class => "btn btn-primary" %>
      <%= link_to 'Cancel', patient_path(@patient), :class => "btn btn-default" %>
    </div>
  </div>

  

<% end %>

app/views/encounters/edit.html.erb
<div class="row">
    <h1>Editing Encounter</h1>
    <%= render 'form', encounter: @encounter %>
</div>

app/views/encounters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Encounters</h1>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Visit number</th>
      <th>Admitted at</th>
      <th>Discharged at</th>
      <th>Location</th>
      <th>Room</th>
      <th>Bed</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encounters.each do |encounter| %>
      <tr>
        <td><%= encounter.visit_number %></td>
        <td><%= encounter.admitted_at %></td>
        <td><%= encounter.discharged_at %></td>
        <td><%= encounter.location %></td>
        <td><%= encounter.room %></td>
        <td><%= encounter.bed %></td>
        <td>
          <a href="patients/<%= encounter.patient.id =%>">
            <%= encounter.patient.first_name + ' ' + encounter.patient.last_name %>
          </a>
        </td>
        <td><%= link_to 'Show', encounter %></td>
        <td><%= link_to 'Edit', edit_encounter_path(encounter) %></td>
        <td><%= link_to 'Destroy', encounter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Encounter', new_encounter_path %>

app/views/encounters/new.html.erb
<div class="row">
    <h1>New Encounter - <%= @patient.first_name + ' ' + @patient.last_name %></h1>
    <%= render 'form', encounter: @encounter %>
</div>

app/views/encounters/show.html.erb
<div class="row">

  <h1>Encounter Details - (<%= @patient.first_name + ' ' + @patient.last_name %>)</h1>

  <% if notice.present? then %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>

  <dl class="dl-horizontal col-sm-12">
    <dt>Visit Number</dt>
    <dd><%= @encounter.visit_number %></dd>
    <dt>Admitted At</dt>
    <dd><%= @encounter.admitted_at %></dd>
    <dt>Discharged At</dt>
    <dd><%= @encounter.discharged_at %></dd>
    <dt>Location</dt>
    <dd><%= @encounter.location %></dd>
    <dt>Room</dt>
    <dd><%= @encounter.room %></dd>
    <dt>Bed</dt>
    <dd><%= @encounter.bed %></dd>
  </dl>

  <%= link_to 'Edit', edit_encounter_path(@encounter), :class => "btn btn-primary" %>
  <%= link_to 'Destroy', @encounter, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
  <%= link_to 'Back', @patient, :class => "btn btn-default" %>

</div>

app/views/home/index.html.erb
<div class="row">
    <h1>ThinkResearch - Question 1: Programming a Web Application</h1>
</div>
<div class="row">
    <pre>Find me in app/views/home/index.html.erb</pre>
</div>
<div class="row">
    <form class="pad-bottom">
        <button class="btn btn-primary" role="button">Add Patient</button>
    </form>
</div>
<div class="row">
    <table class="table table-condensed table-striped">
        <tr>
            <th>MRN</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Actions</th>
        </tr>
        <!-- repeating for model -->
        <tr>
            <td>THC123</td>
            <td>Sandy</td>
            <td>Aria</td>
            <td>
                <div>
                    <a href="#">Show</a> | <a href="#">Edit</a> | <a href="#">Destroy</a>
                </div>
            </td>
        </tr>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThinkResearch</title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for patient, :html => {:class => "form-horizontal"} do |f| %>
  
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :mrn, :class => "col-sm-2 control-label capital" %>
    <div class="col-sm-10">
      <%= f.text_field :mrn, :class => "form-control", :placeholder => "MRN", :required => true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :first_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, :class => "form-control", :placeholder => "First Name", :required => true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :middle_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :middle_name, :class => "form-control", :placeholder => "Middle Name" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :last_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, :class => "form-control", :placeholder => "Last Name", :required => true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :height, :class => "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.number_field :height, :class => "form-control", :placeholder => "Height" %>
    </div>
    <%= f.label :weight, :class => "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.number_field :weight, :class => "form-control", :placeholder => "Weight" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit params[:action] == "new" ? "Submit" : "Update", :class => "btn btn-primary" %>
      <%= link_to 'Cancel', root_url, :class => "btn btn-default", :role => "button" %>
    </div>
  </div>
  
<% end %>

app/views/patients/edit.html.erb
<div class="row">
    <h1>Editing Patient</h1>
    <%= render 'form', patient: @patient %>
</div>

app/views/patients/index.html.erb
<div class="row">

  <h1>Patients</h1>

  <div class="default-pad-bottom">
    <%= link_to 'Add Patient', new_patient_path, :class => "btn btn-primary", :role => "button" %>
  </div>

  <% if notice.present? then %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>

  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th>MRN</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @patients.each do |patient| %>
        <tr>
          <td><%= patient.mrn %></td>
          <td><%= patient.first_name %></td>
          <td><%= patient.last_name %></td>
          <td><%= link_to 'Show', patient %></td>
          <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
          <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/patients/new.html.erb
<div class="row">
    <h1>New Patient</h1>
    <%= render 'form', patient: @patient %>
</div>

app/views/patients/show.html.erb
<div class="row">

  <h1>Patient Details</h1>

  <% if notice.present? then %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>

  <dl class="dl-horizontal col-sm-12">
    <dt>MRN</dt>
    <dd><%= @patient.mrn %></dd>
    <dt>First Name</dt>
    <dd><%= @patient.first_name %></dd>
    <dt>Middle Name</dt>
    <dd><%= @patient.middle_name %></dd>
    <dt>Last Name</dt>
    <dd><%= @patient.last_name %></dd>
    <dt>Height</dt>
    <dd><%= @patient.height %></dd>
    <dt>Weight</dt>
    <dd><%= @patient.weight %></dd>
  </dl>

  
  <div class="default-pad-bottom">
    <%= link_to "Add Encounter", new_encounter_path(:patient_id => @patient.id), :class => "btn btn-primary" %>
  </div>
  
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>Visit Number</th>
          <th>Admitted At</th>
          <th>Discharged At</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% if @patient.encounters.any? then %>
          <% @patient.encounters.each do |encounter| %>
            <tr>
              <td><%= encounter.visit_number %></td>
              <td><%= encounter.admitted_at %></td>
              <td><%= encounter.discharged_at %></td>
              <td><%= link_to 'Show', encounter %></td>
              <td><%= link_to 'Edit', edit_encounter_path(encounter) %></td>
              <td><%= link_to 'Destroy', encounter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="6">No Encounters</td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <%= link_to 'Back', root_url, :class => "btn btn-default" %>

</div>